chore: deploy-bff.yamlのログ出力形式を修正
debug

debug

fix: 変数命名ミス

chore: deploy-previewをdeploy-stagingに変更し、関連する環境設定を更新

chore: SOPSシークレットの抽出とmain.wasmの存在確認を追加

chore: deploy-bff.yamlの条件式を修正し、bunからbunxに変更

update dependencies

chore: deploy-bff.yamlに環境変数設定のステップを追加し、同時実行の設定を追加

chore: deploy-website.yamlから不要な空行を削除

chore: deploy-bff.yamlのビルドログ出力の変数名を修正

chore: deploy-bff.yamlにコミットハッシュを環境変数として追加し、サーバーのレスポンスヘッダーに含める

chore: deploy-bff.yamlのログ出力形式を修正し、EOLの引用符を追加

debug

diff --git a/.github/workflows/deploy-bff.yaml b/.github/workflows/deploy-bff.yaml
--- a/.github/workflows/deploy-bff.yaml
+++ b/.github/workflows/deploy-bff.yaml
@@ -14,11 +14,15 @@ on:
         required: false
         default: false
         type: boolean
-      deploy-preview:
-        description: "Deploy to preview"
+      deploy-staging:
+        description: "Deploy to staging"
         required: false
         default: false
         type: boolean
+
+concurrency:
+  group: "deploy-bff"
+  cancel-in-progress: false
 
 jobs:
   define-matrix:
@@ -27,7 +31,7 @@ jobs:
     outputs:
       environments: ${{ steps.define-matrix.outputs.environments }}
       deploy-production: ${{ steps.define-matrix.outputs.deploy-production }}
-      deploy-preview: ${{ steps.define-matrix.outputs.deploy-preview }}
+      deploy-staging: ${{ steps.define-matrix.outputs.deploy-staging }}
     steps:
       - name: Define matrix
         id: define-matrix
@@ -35,16 +39,16 @@ jobs:
           environments=()
           # workflow_dispatchの場合
           if [ "${{ inputs.deploy-production }}" = "true" ]; then
-            if [ "${{ inputs.deploy-preview }}" = "true" ]; then
-              environments+=("preview")
-            elif [ "${{ inputs.deploy-preview }}" = "false" ]; then
+            if [ "${{ inputs.deploy-staging }}" = "true" ]; then
+              environments+=("staging")
+            elif [ "${{ inputs.deploy-production }}" = "true" ]; then
               environments+=("production")
             fi
           # pushの場合
           elif [ "${{ github.event_name }}" = "push" ]; then
             environments+=("production")
           elif [ "${{ github.event_name }}" = "pull_request" ]; then
-            environments+=("preview")
+            environments+=("staging")
           fi
 
           # 空だった場合はエラー
@@ -55,17 +59,25 @@ jobs:
 
           echo "Deploying to ${environments[@]}"
           # JSONに変換し、環境変数にセット
-          echo "platforms=$(jq -c -n '$ARGS.positional' --args "${environments[@]}")" >> $GITHUB_OUTPUT
+          echo "environments=$(jq -c -n '$ARGS.positional' --args "${environments[@]}")" >> $GITHUB_OUTPUT
 
-
-          echo "deploy-production=$(environments[@] | contains('production'))" >> $GITHUB_OUTPUT
-          echo "deploy-preview=$(environments[@] | contains('preview'))" >> $GITHUB_OUTPUT
+          function has_value() {
+            local target="$1"
+            local value="$2"
+            for element in $target; do
+              if [ "$element" = "$value" ]; then
+                echo "true"
+                return
+              fi
+            done
+            echo "false"
+          }
 
 
   start-deploy-website:
     needs:
       - define-matrix
-    if: ${{ needs.define-matrix.outputs.deploy-production }}
+    if: ${{ contains(fromJson(needs.define-matrix.outputs.environments), 'production') }}
     runs-on: ubuntu-24.04
     timeout-minutes: 1
     outputs:
@@ -88,7 +100,7 @@ jobs:
       matrix:
         environment: ${{ fromJson(needs.define-matrix.outputs.environments) }}
     outputs:
-      build_log: ${{ steps.build-dart-engine.outputs.build_log }}
+      log: ${{ steps.build-dart-engine.outputs.LOG }}
     runs-on: ubuntu-24.04
     steps:
       # https://github.com/actions/checkout
@@ -135,6 +147,8 @@ jobs:
       deployment_url: ${{ steps.extract-deployment-url.outputs.DEPLOYMENT_URL }}
       logs: ${{ steps.extract-logs.outputs.LOG }}
     runs-on: ubuntu-24.04
+    env:
+      MISE_ENV: ci
     steps:
       # https://github.com/actions/checkout
       - name: Checkout
@@ -146,40 +160,62 @@ jobs:
           name: bff-engine-artifact
           path: bff/bridge/engine-artifact
 
+      - name: Extract SOPS secrets
+        run: |
+          mkdir -p ~/.config/mise
+          echo "${{ secrets.SOPS_FILE }}" > ~/.config/mise/flutterkaigi.txt
+
       # https://github.com/jdx/mise-action
       - name: Install Mise dependencies
         uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11
         with:
           install_args: "bun"
 
+      - name: Set environment variables
+        run: |
+          for line in $(mise env --dotenv); do
+            echo $line >> "$GITHUB_ENV"
+            echo "::add-mask::${line#*=}"
+          done
+
       - name: Install dependencies
         working-directory: bff/bridge
         run: bun install --frozen-lockfile
 
-      - name: Deploy BFF(staging)
+      - name: Check main.wasm exists
+        working-directory: bff/bridge/engine-artifact
+        run: |
+          if [ ! -f "main.wasm" ]; then
+            echo "Error: main.wasm not found!"
+            exit 1
+          fi
+
+      - name: Deploy BFF (staging)
         id: deploy-bff-staging
         working-directory: bff/bridge
+        if: ${{ matrix.environment == 'staging' }}
         run: |
           {
             echo "LOG<<EOL"
-            bun run \
-              wrangler deploy \
+            bunx wrangler versions upload \
               --env staging \
-              --minify
+              --var COMMIT_HASH:$(git rev-parse HEAD) \
+              --minify 2>&1
             echo "EOL"
           } | tee -a $GITHUB_OUTPUT
 
 
-      - name: Deploy BFF(production)
+      - name: Deploy BFF (production)
         id: deploy-bff-production
         working-directory: bff/bridge
+        if: ${{ matrix.environment == 'production' }}
         run: |
           {
             echo "LOG<<EOL"
-            bun run \
-              wrangler deploy \
+            bunx wrangler deploy \
               --env production \
-              --minify
+              --var COMMIT_HASH:$(git rev-parse HEAD) \
+              --minify 2>&1
             echo "EOL"
           } | tee -a $GITHUB_OUTPUT
 
@@ -193,7 +229,7 @@ jobs:
           fi
 
           # `https://` を含む最初の行だけを抽出し、DEPLOYMENT_URLに格納
-          DEPLOYMENT_URL=$(echo "$LOG" | grep -o 'https://[^ ]*' | head -n 1)
+          DEPLOYMENT_URL=$(echo $LOG | grep -o 'https://[^ ]*' | head -n 1)
           echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
 
       - name: Set logs
@@ -203,7 +239,7 @@ jobs:
           PRODUCTION_LOG: ${{ steps.deploy-bff-production.outputs.log }}
         run: |
           {
-            echo "LOG<<EOL"
+            echo "LOG<<'EOL'"
             if [ "${{ env.STAGING_LOG }}" != "" ]; then
               echo "${{ env.STAGING_LOG }}"
             fi
@@ -235,7 +271,7 @@ jobs:
           <summary><h2>📦️ Build Logs</h2></summary>
 
           \`\`\`log
-          ${{ needs.build-dart-engine.outputs.build_log }}
+          ${{ needs.build-dart-engine.outputs.log }}
           \`\`\`
           </details>
 
@@ -265,7 +301,7 @@ jobs:
       - build-dart-engine
       - start-deploy-website
       - deploy-bff
-    if: ${{ needs.define-matrix.outputs.deploy-production }}
+    if: ${{ contains(fromJson(needs.define-matrix.outputs.environments), 'production') }}
     timeout-minutes: 1
     steps:
       - name: Get previous jobs status
